#!/bin/bash
# Note that when this script is run from cron, the  /usr/local/bin is not in the PATH variable.
# $(basename $0) can be used to get the name of this script without any path prefix.

# Start with removing previous uploads to  Google Drive to prevent filling up Google Drive
# Define the number of files to keep, excluding the new file to be uploaded.
numberOfFilesToKeep=2

# Store all id's of the dfrobot_pivid.mp4 files on Google Drive in an array
# The 'drive' utility will list the newest files first.
myArray=( $(/usr/local/bin/drive list -t dfrobot_pivid.mp4 | sed -n 's/^\([^ ]*\).*$/\1/p') )

# Go through the array of id's from back to forth, to handle the oldest file first.
echo "***** log file created at $(date) *****" > /home/pi/log/$(basename $0)_log.txt
for (( i=${#myArray[@]}-1; i>$numberOfFilesToKeep; i-- )); do
    /usr/local/bin/drive delete -i ${myArray[i]} >> /home/pi/log/$(basename $0)_log.txt 2>&1
done
