#!/bin/bash
# This script purges DFRobot uploaded files on Google Drive.
# The first parameter indicates the name of the file to purge. The name must start with "dfrobot_".
# The second parameter indicates the number of files to keep after the purge. This must be >= 1.
# This script can be called from a CGI script called from an html form action. The stdout generated by this script is sent back to the browser,
# therefore it is important to capture all stdout output which must not be returned to the html.
# This can be done using '> /dev/null 2>&1' or writing to a logfile.
# Note that when this script is run from cron, the  /usr/local/bin is not in the PATH variable.
# $(basename $0) can be used to get the name of this script without any path prefix.

prompt=$(basename $0)
# Reset the log file to zero length if the size gets too large.
if [ $(stat -c %s /home/pi/log/dfrobot_log.txt) -gt 1000000 ]
then
    echo -e "***** $(date), $prompt: START LOG  *****" > /home/pi/log/dfrobot_log.txt
else
    echo -e "\n***** $(date), $prompt: START LOG  *****" >> /home/pi/log/dfrobot_log.txt
fi

# For safety check parameters!
# Check if first parameter starts with "dfrobot_" and number of files to keep >= 1 else do not purge anything and exit.
if [[ $1 != dfrobot_* || ! $2 -ge 1 ]]
then
    echo "***** $(date), $prompt: not going to purge, illegal parameters: $1, $2" >> /home/pi/log/dfrobot_log.txt
    exit 0
fi

# Define the number of files to keep after the purge.
numberOfFilesToKeep=$2

# Store all id's of the $1 files on Google Drive in an array
# The 'drive' utility will list the newest files first.
fileArray=( $(/usr/local/bin/drive list -t $1 | sed -n 's/^\([^ ]*\).*$/\1/p') )

echo "***** $(date), $prompt: $((${#fileArray[@]}-1)) $1 files found on Google Drive" >> /home/pi/log/dfrobot_log.txt

# Purge files.
# Go through the array of id's from back to forth, to handle the oldest file first.
for (( i=${#fileArray[@]}-1; i>$numberOfFilesToKeep; i-- )); do
    echo "***** $(date), $prompt: going to call 'drive' to purge" >> /home/pi/log/dfrobot_log.txt
    /usr/local/bin/drive delete -i ${fileArray[i]} >> /home/pi/log/dfrobot_log.txt 2>&1
done
